Test of inlining a function that references err.Error,
which is often a special case because it has no position.

Previously the output was
  var _ = (io.EOF.Error())
but this relied on a bug in pure().
A follow-up analysis of callee effect ordering
will re-enable this "style optimization".

-- go.mod --
module testdata
go 1.12

-- a/a.go --
package a

import "io"

var _ = getError(io.EOF) //@ inline(re"getError", getError)

func getError(err error) string { return err.Error() }

-- getError --
package a

import "io"

var _ = func(err error) string { return err.Error() }(io.EOF) //@ inline(re"getError", getError)

func getError(err error) string { return err.Error() }
